@props(['title' => null])

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ $title ? "{$title} - ".config('app.name') : config('app.name') }}</title>

    @vite(['resources/css/app.css', 'resources/js/app.js'])
    {{ Vite::fonts('ibm-plex-sans-arabic') }}
</head>
<body class="min-h-screen bg-bg font-sans text-ink antialiased">
    <div class="grid min-h-screen lg:grid-cols-2">
        {{--
            The wood panel. The grain is generated by an SVG turbulence filter,
            not an image file — nothing is downloaded, it scales to any screen,
            and it costs a few hundred bytes. Hidden on phones, where the
            screen belongs to the form.
        --}}
        <aside class="relative hidden overflow-hidden bg-brand lg:flex lg:flex-col lg:justify-between lg:p-12">
            <svg class="pointer-events-none absolute inset-0 h-full w-full opacity-25 mix-blend-overlay" aria-hidden="true" preserveAspectRatio="none">
                <defs>
                    <filter id="wood-grain">
                        {{-- Stretched noise: dense across, sparse down = long grain lines. --}}
                        <feTurbulence type="fractalNoise" baseFrequency="0.86 0.011" numOctaves="4" seed="7" result="noise"/>
                        <feColorMatrix type="saturate" values="0"/>
                    </filter>
                </defs>
                <rect width="100%" height="100%" filter="url(#wood-grain)"/>
            </svg>

            {{-- A few long rings, like the edge of a cut board. --}}
            <svg class="pointer-events-none absolute inset-y-0 start-0 h-full w-2/3 opacity-20" viewBox="0 0 400 800" fill="none" preserveAspectRatio="none" aria-hidden="true">
                @foreach ([40, 95, 155, 220, 290, 365] as $offset)
                    <path d="M{{ $offset }} -40 C {{ $offset + 70 }} 180, {{ $offset - 50 }} 420, {{ $offset + 60 }} 840"
                          class="stroke-brand-text" stroke-width="1.5"/>
                @endforeach
            </svg>

            <div class="relative flex items-center gap-3">
                <span class="flex size-11 items-center justify-center rounded-xl bg-brand-text/15 text-lg font-bold text-brand-text ring-1 ring-brand-text/20">D</span>
                <span class="text-xl font-bold tracking-wide text-brand-text">{{ config('app.name') }}</span>
            </div>

            <div class="relative">
                <h2 class="text-3xl font-bold leading-snug text-brand-text">نظام إدارة وحسابات<br>ورشة الأثاث</h2>
                <p class="mt-4 max-w-md text-sm leading-relaxed text-brand-text/70">
                    من أول شراء الخامة لحد صافي الربح ونصيب الشركاء — كل رقم في مكانه، وكل جنيه متتبّع.
                </p>

                <ul class="mt-8 space-y-3 text-sm text-brand-text/80">
                    @foreach (['العملاء والغرف والتكلفة الفعلية', 'المخزن والمشتريات المطلوبة', 'الخزنة والمصروفات والأرباح'] as $line)
                        <li class="flex items-center gap-2.5">
                            <span class="size-1.5 rounded-full bg-brand-text/50" aria-hidden="true"></span>{{ $line }}
                        </li>
                    @endforeach
                </ul>
            </div>

            <p class="relative text-xs text-brand-text/40">كل البيانات متخزَّنة على جهازك.</p>
        </aside>

        <main class="flex items-center justify-center px-5 py-10">
            <div class="w-full max-w-sm">
                {{-- The brand repeats here for phones, where the panel is hidden. --}}
                <div class="mb-8 flex items-center justify-center gap-3 lg:hidden">
                    <span class="flex size-10 items-center justify-center rounded-xl bg-brand text-base font-bold text-brand-text">D</span>
                    <span class="text-xl font-bold tracking-wide text-ink">{{ config('app.name') }}</span>
                </div>

                {{ $slot }}
            </div>
        </main>
    </div>
</body>
</html>
